export const names = [
{ name: "John", type: "First Name"},
{ name: "Noah", type: "First Name"},
{ name: "Olivia", type: "First Name"},
{ name: "Liam", type: "First Name"},
{ name: "Ava", type: "First Name"},
{ name: "Sophia", type: "First Name"},
{ name: "William", type: "First Name"},
{ name: "Isabella", type: "First Name"},
{ name: "Mason", type: "First Name"},
{ name: "James", type: "First Name"},
{ name: "Elijah", type: "First Name"},
{ name: "Charlotte", type: "First Name"},
{ name: "Benjamin", type: "First Name"},
{ name: "Amelia", type: "First Name"},
{ name: "Lucas", type: "First Name"},
{ name: "Michael", type: "First Name"},
{ name: "Abigail", type: "First Name"},
{ name: "Alexander", type: "First Name"},
{ name: "Ethan", type: "First Name"},
{ name: "Harper", type: "First Name"},
{ name: "Ryan", type: "First Name"},
{ name: "Doe", type: "Last Name"},
{ name: "Smith", type: "Last Name"},
    { name: "Johnson", type: "Last Name"},
    { name: "Williams", type: "Last Name"},
    { name: "Jones", type: "Last Name"},
    { name: "Brown", type: "Last Name"},
    { name: "Davis", type: "Last Name"},
    { name: "Miller", type: "Last Name"},
    { name: "Wilson", type: "Last Name"},
    { name: "Moore", type: "Last Name"},
    { name: "Taylor", type: "Last Name"},
    { name: "Anderson", type: "Last Name"},
    { name: "Thomas", type: "Last Name"},
    { name: "Jackson", type: "Last Name"},
    { name: "White", type: "Last Name"},
    { name: "Harris", type: "Last Name"},
    { name: "Martin", type: "Last Name"},
    { name: "Thompson", type: "Last Name"},
    { name: "Garcia", type: "Last Name"},
    { name: "Martinez", type: "Last Name"},
{ name: "Professional", type: "Profession"},
  { name: "Engineer", type: "Profession"},
    { name: "Doctor", type: "Profession"},
    { name: "Teacher", type: "Profession"},
    { name: "Lawyer", type: "Profession"},
    { name: "Artist", type: "Profession"},
    { name: "Accountant", type: "Profession"},
    { name: "Writer", type: "Profession"},
    { name: "Nurse", type: "Profession"},
    { name: "Scientist", type: "Profession"},
    { name: "Chef", type: "Profession"},
    { name: "Police Officer", type: "Profession"},
    { name: "Firefighter", type: "Profession"},
    { name: "Entrepreneur", type: "Profession"},
    { name: "Architect", type: "Profession"},
    { name: "Musician", type: "Profession"},
    { name: "Athlete", type: "Profession"},
    { name: "Psychologist", type: "Profession"},
    { name: "Dentist", type: "Profession"},
    { name: "Pilot", type: "Profession"},
{ name: "Joe's Stuff", type: "Company"},
{ name: "Tech Solutions", type: "Company"},
   { name: "Healthcare Associates", type: "Company"},
    { name: "Global Innovations", type: "Company"},
    { name: "Bright Horizons", type: "Company"},
    { name: "Silver Star Enterprises", type: "Company"},
    { name: "Spectrum Technologies", type: "Company"},
    { name: "Blue Sky Ventures", type: "Company"},
    { name: "Sunrise Solutions", type: "Company"},
    { name: "Peak Performance Partners", type: "Company"},
    { name: "Vivid Visionaries", type: "Company"},
    { name: "Pinnacle Productions", type: "Company"},
    { name: "Eagle Eye Enterprises", type: "Company"},
    { name: "Northern Lights Innovations", type: "Company"},
    { name: "Crystal Clear Consulting", type: "Company"},
    { name: "Golden Gate Group", type: "Company"},
    { name: "Emerald Edge Enterprises", type: "Company"},
    { name: "DreamWorks Dynamics", type: "Company"},
    { name: "Infinite Insights", type: "Company"},
    { name: "Zenith Solutions", type: "Company"},
];