export const upgrades = [
//Foam Finger
  { name: "Custom Design", price: 100, type: "motivation", area:"foamfinger", purchased: false, description: "Upgrade your foam finger with a custom design (+2/click foam finger).", effect: 2 },
  { name: "Signature Autograph", price: 200, type: "motivation", area:"foamfinger",purchased: false, description: "Get your foam finger signed by a celebrity! (+2/click foam finger)", effect: 2 },
  { name: "Colorful Patterns", price: 300, type: "motivation", area:"foamfinger",purchased: false, description: "Add colorful patterns to your foam finger (+2/click foam finger).", effect: 2 },
  { name: "Team Logo", price: 400, type: "motivation", area:"foamfinger",purchased: false, description: "Display your favorite team's logo on your foam finger (+2/click foam finger).", effect: 2 },
  { name: "Double-Sided Print", price: 500, type: "motivation",area:"foamfinger", purchased: false, description: "Upgrade to a double-sided foam finger (+2/click foam finger).", effect: 2 },
  { name: "Glow-in-the-Dark", price: 600, type: "motivation",area:"foamfinger", purchased: false, description: "Make your foam finger glow in the dark! (+2/click foam finger)", effect: 2 },
  { name: "Sound Effects", price: 700, type: "motivation", area:"foamfinger",purchased: false, description: "Add sound effects to your foam finger (+2/click foam finger).", effect: 2 },
  { name: "LED Lights", price: 800, type: "motivation", area:"foamfinger",purchased: false, description: "Illuminate your foam finger with LED lights (+2/click foam finger).", effect: 2 },
  { name: "Superhero Theme", price: 900, type: "motivation", area:"foamfinger",purchased: false, description: "Turn your foam finger into a superhero's weapon! (+2/click foam finger)", effect: 2 },
  { name: "Limited Edition", price: 1000, type: "motivation", area:"foamfinger",purchased: false, description: "Get your hands on a limited edition foam finger (+2/click foam finger).", effect: 2 },
 // Motivation Poster
{ name: "Inspirational Quotes", price: 100, type: "motivation", area: "motivationPoster", purchased: false, description: "Decorate your wall with inspiring quotes (+2/sec motivation).", effect: 2 },
  { name: "Artistic Illustrations", price: 150, type: "motivation", area: "motivationPoster", purchased: false, description: "Hang artistic illustrations for motivation (+2/sec motivation).", effect: 2 },
  { name: "Nature Scenes", price: 200, type: "motivation", area: "motivationPoster", purchased: false, description: "Adorn your room with serene nature scenes (+2/sec motivation).", effect: 2 },
  { name: "Success Stories", price: 250, type: "motivation", area: "motivationPoster", purchased: false, description: "Display success stories for constant inspiration (+2/sec motivation).", effect: 2 },
  { name: "Vision Board", price: 300, type: "motivation", area: "motivationPoster", purchased: false, description: "Create a vision board to visualize your goals (+2/sec motivation).", effect: 2 },
  { name: "Motivational Artwork", price: 350, type: "motivation", area: "motivationPoster", purchased: false, description: "Hang motivational artwork to stay inspired (+2/sec motivation).", effect: 2 },
  { name: "Personal Mantras", price: 400, type: "motivation", area: "motivationPoster", purchased: false, description: "Display personal mantras for daily motivation (+2/sec motivation).", effect: 2 },
  { name: "Fitness Inspirations", price: 450, type: "motivation", area: "motivationPoster", purchased: false, description: "Hang fitness inspirations to stay active (+2/sec motivation).", effect: 2 },
  { name: "Goal Setting Tips", price: 500, type: "motivation", area: "motivationPoster", purchased: false, description: "Display tips for effective goal setting (+2/sec motivation).", effect: 2 },
  { name: "Positive Affirmations", price: 550, type: "motivation", area: "motivationPoster", purchased: false, description: "Surround yourself with positive affirmations (+2/sec motivation).", effect: 2 },
  { name: "Dream Board", price: 600, type: "motivation", area: "motivationPoster", purchased: false, description: "Create a dream board to visualize your aspirations (+2/sec motivation).", effect: 2 },
  { name: "Motivational Quotes", price: 650, type: "motivation", area: "motivationPoster", purchased: false, description: "Hang motivational quotes for daily inspiration (+2/sec motivation).", effect: 2 },
  { name: "Entrepreneurial Inspiration", price: 700, type: "motivation", area: "motivationPoster", purchased: false, description: "Find entrepreneurial inspiration for your projects (+2/sec motivation).", effect: 2 },
  { name: "Wisdom of Elders", price: 750, type: "motivation", area: "motivationPoster", purchased: false, description: "Display the wisdom of elders for guidance (+2/sec motivation).", effect: 2 },
  { name: "Daily Affirmations", price: 800, type: "motivation", area: "motivationPoster", purchased: false, description: "Start your day with positive daily affirmations (+2/sec motivation).", effect: 2 },
];
